ptf ~
cap_sol_progr__1      ~cap_sol_progr_1~    
cap_sol_progr__2      ~cap_sol_progr_2~    
cap_sol_progr__8      ~cap_sol_progr_8~    
equ_ruis_perc__1      ~equ_ruis_perc_1~    
equ_ruis_perc__2      ~equ_ruis_perc_2~    
equ_ruis_perc__8      ~equ_ruis_perc_8~    
t_demi_percol__1      ~t_demi_percol_1~    
t_demi_percol__2      ~t_demi_percol_2~    
t_demi_percol__8      ~t_demi_percol_8~    